# .gitea/workflows/QCA-6.12-VIKINGYFY.yml
name: QCA-6.12-VIKINGYFY

on:
  workflow_dispatch:
    inputs:
      PACKAGE:
        description: '手动调整插件包，多个请用\n符号隔开。'
        required: false
        type: string
      TEST:
        description: '仅输出配置文件，不编译固件。'
        default: 'false'
        required: false
        type: boolean

jobs:
  config:
    name: ${{ matrix.CONFIG }}
    runs-on: buildx
    strategy:
      fail-fast: false
      matrix:
        CONFIG: [IPQ60XX-NOWIFI, IPQ60XX-WIFI]
        SOURCE: [VIKINGYFY/immortalwrt]
        BRANCH: [main]

    uses: ./.gitea/workflows/WRT-CORE.yml
    with:
      WRT_CONFIG: ${{ matrix.CONFIG }}
      WRT_THEME: argon
      WRT_NAME: DAE-WRT
      WRT_SSID: DAE-WRT
      WRT_WORD: 12345678
      WRT_IP: 192.168.10.1
      WRT_PW: 无
      WRT_REPO: https://github.com/${{ matrix.SOURCE }}.git
      WRT_BRANCH: ${{ matrix.BRANCH }}
      WRT_SOURCE: ${{ matrix.SOURCE }}
      WRT_PACKAGE: ${{ inputs.PACKAGE }}
      WRT_TEST: ${{ inputs.TEST }}
      CI_NAME: ${{ gitea.workflow }}
