#!/bin/sh

[ -x /etc/init.d/tailscale-lan-tailnet ] || exit 0

/etc/init.d/tailscale-lan-tailnet enable >/dev/null 2>&1 || exit 1
/etc/init.d/tailscale-lan-tailnet start >/dev/null 2>&1 || exit 1

exit 0
