#!/bin/sh

[ -d /etc/tailscale ] || mkdir -p /etc/tailscale

if [ -x /etc/init.d/headscale-auto-enroll ]; then
	/etc/init.d/headscale-auto-enroll enable >/dev/null 2>&1 || true
	/etc/init.d/headscale-auto-enroll start >/dev/null 2>&1 || true
fi

exit 0
