#!/bin/sh

[ -x /etc/init.d/tailscale-state-persist ] || exit 0
/etc/init.d/tailscale-state-persist enable >/dev/null 2>&1 || true
/etc/init.d/tailscale-state-persist start >/dev/null 2>&1 || true
exit 0
