#!/bin/sh /etc/rc.common
START=89
USE_PROCD=1

start_service() {
  # Prevent the package's S90 from starting against a fresh unprepared DB.
  /etc/init.d/gecoosac disable
  procd_open_instance
  procd_set_param command /usr/sbin/gecoosac-auto
  procd_set_param stdout 1
  procd_set_param stderr 1
  procd_close_instance
}
