#!/bin/sh /etc/rc.common

START=98
STOP=10
USE_PROCD=1

start_service() {
	procd_open_instance
	procd_set_param command /usr/sbin/headscale-auto-enroll
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}

restart() {
	stop
	start
}
