#!/bin/sh /etc/rc.common
START=99
USE_PROCD=1

start_service() {
  procd_open_instance
  procd_set_param command /usr/sbin/nikki-subscription-sync
  procd_set_param respawn 0 0 0
  procd_close_instance
}
