# SPDX-License-Identifier: MIT
# Copyright (C) 2026 VIKINGYFY

name: Auto-Clean

on:
  #自动清理：每周一早上4点
  schedule:
    - cron: 0 20 * * 0
  #手动清理
  workflow_dispatch:
permissions:
  actions: write
  contents: read

jobs:
  auto_clean:
    runs-on: ubuntu-22.04
    steps:
      - name: Delete old workflow runs
        uses: ophub/delete-releases-workflows@185ead47518014ad09d25f358e70353483bdb22f # v0.1.0
        with:
          gh_token: ${{secrets.GITHUB_TOKEN}}
          delete_releases: false
          delete_workflows: true
          # Deleting a workflow run also deletes its private firmware artifacts.
          workflows_keep_day: 30
